package uk.ac.ebi.pride.spectracluster.hadoop;

import org.apache.hadoop.conf.*;
import org.apache.hadoop.io.*;

import java.io.*;
import java.util.*;

/**
 * uk.ac.ebi.pride.spectracluster.hadoop.PartitioningTests
 * We are having problems with partitioning -
 * This code reads the sequence files generated by a job and looks at the partition distribution
 * It does not use hadoop for speed and debugging
 *
 * @author Steve Lewis
 * @date 8/30/13
 */
public class PartitioningTests {

    private final List<String> keys = new ArrayList<String>();
    private final File targetDirectory;
    private final Configuration conf = new Configuration();
    private final Text onlyKey = new Text();
    @SuppressWarnings("UnusedDeclaration")
    private final Text onlyValue = new Text();


    public PartitioningTests(File targetDirectory) {
        this.targetDirectory = targetDirectory;
    }

    public void addKey(String key)   {
        keys.add(key);
    }

    protected void writeKeys(File out) {
        try {
            PrintWriter pout = new PrintWriter(new FileWriter(out)) ;
            for (String key : keys) {
                pout.println(key);
            }
            pout.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }


    public void readKeys() {
        File[] files = targetDirectory.listFiles();
        if (files == null)
            throw new IllegalArgumentException("Directory is empty" + targetDirectory.getAbsolutePath());
        //noinspection ForLoopReplaceableByForEach
        for (int i = 0; i < files.length; i++) {
            File file = files[i];
            readKeys(file);
        }
    }

    public void readKeys(File file)  throws RuntimeException
    {
        SequenceFile.Reader rdr = SpectraHadoopUtilities.buildSequenceFileReader(file, conf);
        try {
            while (rdr.next(onlyKey)) {
                String key = onlyKey.toString();
                addKey(key);
            }
        } catch (IOException e) {
            throw new UnsupportedOperationException(e);
        } finally {
            try {
                rdr.close();
            } catch (IOException e) {
                //noinspection ThrowFromFinallyBlock
                throw new RuntimeException(e);

            }
        }


    }

    public static void main(String[] args) {
        File f = new File(args[0]);
        if (!f.exists() || !f.isDirectory())
            throw new IllegalArgumentException("Directory does not exits " + args[0]);
        File out = new File(args[1]);

        PartitioningTests pt = new PartitioningTests(f);
        pt.readKeys();
        pt.writeKeys(out);
    }

}
